name: Build-Test-Release

on:
  push:
    branches:
      - nx_release_2

jobs:
  build-test-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          # TODO do we want to hardcode this though?
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npx nx build @nabalones/language-chooser-react-mui

      # find-language is a dependency of langauge-chooser-react-mui so will have been built in the build step
      - name: Run tests
        run: npx nx test @nabalones/find-language

      - name: Clean up package.json
        run: npm pkg delete devDependencies && npm pkg delete dependencies

      # TODO do we still need this? copied from bloom-player
      - name: Clean up package.json
        run: npm pkg delete scripts && npm pkg delete devDependencies && npm pkg delete dependencies

      - name: Print Environment Info
        run: npx nx report

      - name: Set name and email for git
        run: |
          git config user.name "Github Actions"
          git config user.email "test@example.com"

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx release --yes
# making a change for release
